version: '3'
services:
  web_service:
    build: ./app
    restart: always
    environment:
      - FLAG=${FLAG}
      - FLAG_SECRET=${FLAG_SECRET}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - PGPASSWORD=${DOCKER_PGPASSWORD}
      - FLASK_CORE_CONFIG=/app/web/config.py
    ports:
      - 0.0.0.0:8003:8000
    networks:
      - infra_net
networks:
  infra_net:
    external: true
