version: '3'
services:
  web_service:  # Specify environment variables through the --env-file flag (when its finally released)
    build: ./app
    restart: unless-stopped
    env_file:
      - "${ENV_FILE:-.prod.env}"
    environment:
      - PGPASSWORD=${INFRA_PGPASSWORD:?INFRA_PGPASSWORD envvar required for database updates.}
    ports:
      - 0.0.0.0:${PUBLISH_PORT:?PUBLISH_PORT envvar required for publishing.}:8000
    networks:
      - infra_net
networks:
  infra_net:
    external: true
