version: '3'
services:
  web_service:
    build: ./app
    restart: always
    environment:
      - FLAG=FLAG{REPLACE_ME}
      - FLAG_SECRET=A_BAD_TEMPORARY_SECRET
      - DB_CONNECTION_STRING=postgresql://{{database_user}}:{{database_pass}@database/{{database_name}}
      - PGPASSWORD=***REMOVED***
    ports:
      - 0.0.0.0:8003:8000
    networks:
      - infra_net
networks:
  infra_net:
    external: true
