version: '3'
services:
  web_service:
    build: ./app
    restart: always
    environment:
      - FLAG=I_AM_NOT_A_FLAG
      - FLAG_SECRET=A_BAD_TEMPORARY_SECRET
      - DB_CONNECTION_STRING=postgresql://{{cookiecutter.database_user}}:{{cookiecutter.database_pass}}@database/{{cookiecutter.database_name}}
      - PGPASSWORD=***REMOVED***
    ports:
      - 0.0.0.0:{{cookiecutter.docker_publish_port}}:8000
    networks:
      - infra_net
networks:
  infra_net:
    external: true
